# Generated by Django 4.2.1 on 2023-05-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqli', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='full_name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='std_num',
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='r', max_length=50),
            preserve_default=False,
        ),
    ]
